# Generated by Django 3.1.2 on 2020-11-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_id_number', models.IntegerField()),
                ('client_business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=200)),
                ('client_contacts', models.CharField(max_length=255)),
                ('client_status', models.BooleanField(default=False)),
                ('client_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_id_number', models.IntegerField()),
                ('client_contacts', models.CharField(max_length=255)),
                ('client_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_unit_price', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('product_brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RentsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SalesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ShelfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.IntegerField(unique=True)),
                ('shelf_size', models.CharField(max_length=255)),
                ('shelf_price', models.CharField(max_length=60)),
                ('shelf_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShelfPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ShelvesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PurchasesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.customermodel')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.productmodel')),
                ('shelf_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.shelfmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ClientStockModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.CharField(max_length=255)),
                ('product_description', models.TextField(max_length=255)),
                ('no_of_items', models.IntegerField()),
                ('client_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.clientmodel')),
                ('productmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.productmodel')),
            ],
        ),
    ]
