# Generated by Django 3.1.2 on 2020-11-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clientmodel_clientspage_clientstockmodel_customermodel_customerspage_productmodel_productspage_purch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.IntegerField(unique=True)),
                ('shelf_size', models.CharField(max_length=255)),
                ('shelf_price', models.CharField(max_length=60)),
                ('shelf_description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ClientStockModel',
            new_name='ClientStock',
        ),
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
        migrations.RemoveField(
            model_name='purchasesmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchasesmodel',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='purchasesmodel',
            name='shelf_model',
        ),
        migrations.RenameModel(
            old_name='ClientModel',
            new_name='Client',
        ),
        migrations.DeleteModel(
            name='CustomerModel',
        ),
        migrations.DeleteModel(
            name='PurchasesModel',
        ),
        migrations.DeleteModel(
            name='ShelfModel',
        ),
        migrations.AddField(
            model_name='shelf',
            name='client_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.client'),
        ),
    ]
