# Generated by Django 3.1.2 on 2020-11-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201123_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='client_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.client'),
        ),
    ]
