# Generated by Django 3.1.2 on 2020-11-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_product_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='photo',
            field=models.ImageField(default='images/photo1.jpg', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='shelf_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
