# Generated by Django 3.1.2 on 2020-11-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201123_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_products',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_shelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.shelf'),
            preserve_default=False,
        ),
    ]
