# Generated by Django 3.1.2 on 2020-11-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_productsales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsales',
            name='type_of_payment',
            field=models.CharField(choices=[('Paid to owner', 'M'), ('Cash payment', 'F')], max_length=20),
        ),
    ]
