# Generated by Django 3.1.2 on 2020-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201125_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsales',
            name='customer_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsales',
            name='customer_name',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsales',
            name='no_of_items',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productsales',
            name='type_of_payment',
            field=models.CharField(choices=[('Paid to owner', 'Paid to owner'), ('Cash payment', 'Cash Payment')], max_length=20),
        ),
    ]
