# Generated by Django 3.1.2 on 2020-11-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201125_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSales',
            new_name='ProductSale',
        ),
    ]
