# Generated by Django 3.1.2 on 2020-11-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='client_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.client', unique=True),
        ),
    ]
