# Generated by Django 3.1.2 on 2020-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201125_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='images'),
        ),
    ]
