# Generated by Django 3.1.2 on 2020-11-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20201125_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='photo',
        ),
    ]
