# Generated by Django 3.1.2 on 2020-11-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_shelf_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientStock',
        ),
    ]
