# Generated by Django 3.1.2 on 2020-11-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_delete_clientstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='images/product1.jpg', upload_to='images'),
        ),
    ]
