# Generated by Django 3.1.2 on 2020-11-26 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20201126_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.client')),
                ('shelf_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.shelf')),
            ],
        ),
    ]
