# Generated by Django 3.1.2 on 2020-11-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rentpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
    ]
